version: "3.8"
services:
  igd:
    image: igd-challenge:0.1
    build:
      dockerfile: Dockerfile
      context: .
      target: app
    volumes:
      - ./:/srv/app/
    working_dir: /srv/app/src/
    networks:
      - igd-challenge-network
    tty: true
    stdin_open: true
    ports:
      - 8090:8090
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: igd
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - igd-challenge-network
    restart: unless-stopped

volumes:
  db_data:

networks:
  igd-challenge-network:
    name: igd-challenge-network
    driver: bridge
